### ISSUE TITLE
[EPIC] Introduce Transaction

### ISSUE THREAD

**Issue by gaynetdinov** [gaynetdinov/ex_money#1]
Transaction entity represents a bank transaction. Bank transactions can be fetched from saltedge or created by end user manually. 

- [x] create transactions table with appropriate ecto model => https://github.com/gaynetdinov/ex_money/issues/2
- [x] create worker to fetch transaction from saltedge => https://github.com/gaynetdinov/ex_money/issues/3
- [x] create scheduler to start/stop transaction worker => https://github.com/gaynetdinov/ex_money/issues/4
- [x] create basic CRUD UI for transactions using bootstrap =>
https://github.com/gaynetdinov/ex_money/issues/5
